# CYA against us or stephdewitt's role leaving anything with root:root owernship
- name: Update nvm permissions
  file:
    path: "/home/vagrant/.nvm"
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant

- name: Touch nvm default-packages file
  become_user: vagrant
  file:
    path: "/home/vagrant/.nvm/default-packages"
    state: touch
    mode: '0644'
    modification_time: preserve
    access_time: preserve
    owner: vagrant
    group: vagrant

- name: Ensure yarn is an nvm default-package
  become_user: vagrant
  blockinfile:
    dest: "/home/vagrant/.nvm/default-packages"
    block: |
      yarn
  register: default_packages_updated

- name: Ensure nvm default-packages are installed
  become_user: vagrant
  shell: |
    . /home/vagrant/.nvm/nvm.sh
    nvm use 18.6.0
    nvm exec 18.6.0 npm install --global yarn
  environment:
    NVM_DIR: "/home/vagrant/.nvm"
